import { useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Link, useNavigate, useParams } from "react-router-dom";
import ExploreLayout from "../../components/layout/Explore/Layout";
import ConfirmModal from "../../components/ui/ConfirmModal";
import { couponsApi } from "../../services/coupons";

const editable = ["code", "name", "description", "discount_value", "max_discount", "minimum_purchase", "start_date", "end_date", "usage_limit_total", "usage_limit_per_user"];
export default function EditCoupon() {
  const { couponId } = useParams(); const navigate = useNavigate(); const [form, setForm] = useState({}); const [error, setError] = useState(""); const [confirm, setConfirm] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { couponsApi.organizerCoupon(couponId).then(({ data }) => setForm(data.coupon)).catch(() => setError("Unable to load coupon.")); }, [couponId]);
  const change = (e) => setForm((current) => ({ ...current, [e.target.name]: e.target.value }));
  const validate = () => { if (!/^[A-Za-z0-9-]{3,40}$/.test(form.code || "")) return "Coupon code must use 3-40 letters, numbers, or hyphens."; if (!form.name?.trim()) return "Coupon name is required."; if (!form.start_date || !form.end_date || form.start_date > form.end_date) return "Choose a valid date range."; if (Number(form.discount_value) <= 0 || (form.discount_type === "PERCENTAGE" && Number(form.discount_value) > 100)) return "Enter a valid discount value."; return ""; };
  const submit = (e) => { e.preventDefault(); const message = validate(); setError(message); if (!message) setConfirm(true); };
  const save = async () => { setSaving(true); try { await couponsApi.update(couponId, form); navigate("/coupons", { replace: true, state: { message: "Coupon updated and sent for approval." } }); } catch (e) { const body = e.response?.data; setError(body?.detail || "Unable to update coupon."); } finally { setSaving(false); } };
  return <ExploreLayout><main className="min-h-screen bg-[#0d1418] px-4 pb-16 pt-24 text-white sm:px-8"><div className="mx-auto max-w-5xl"><Link to="/coupons" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-[#00ff85]"><ArrowLeft size={16} /> Back to coupons</Link><h1 className="mt-6 text-3xl font-light">Edit Coupon</h1>{error && <p className="mt-4 rounded-xl border border-red-400/30 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}<form onSubmit={submit} className="mt-6 grid gap-4 rounded-2xl border border-white/10 bg-[#171e25] p-5 sm:grid-cols-2">{editable.map((name) => <label key={name} className={`text-sm text-slate-300 ${name === "description" ? "sm:col-span-2" : ""}`}>{name.replaceAll("_", " ")}<input name={name} type={name.includes("date") ? "date" : name.includes("value") || name.includes("purchase") || name.includes("limit") ? "number" : "text"} value={form[name] ?? ""} onChange={change} disabled={name === "discount_type" && false} className="mt-1.5 w-full rounded-lg border border-white/10 bg-[#111820] px-3 py-2.5 capitalize text-white" /></label>)}<label className="text-sm text-slate-300">Discount type<select name="discount_type" value={form.discount_type || "PERCENTAGE"} onChange={change} className="mt-1.5 w-full rounded-lg border border-white/10 bg-[#111820] px-3 py-2.5 text-white"><option value="PERCENTAGE">Percentage (%)</option><option value="AMOUNT">Fixed amount</option></select></label><div className="flex justify-end gap-3 sm:col-span-2"><Link to="/coupons" className="rounded-lg border border-white/15 px-5 py-2.5">Cancel</Link><button className="rounded-lg bg-[#00ff85] px-5 py-2.5 font-semibold text-black">Save changes</button></div></form></div>{confirm && <ConfirmModal title="Save Coupon Changes?" message="Saving changes will send this coupon back for admin approval." confirmLabel="Save changes" loading={saving} onCancel={() => setConfirm(false)} onConfirm={save} />}</main></ExploreLayout>;
}
